# Generated by Django 3.2.25 on 2024-11-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstitute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute', models.CharField(max_length=500, unique=True)),
                ('group', models.ForeignKey(blank=True, help_text='Select the group that will manage requests for this Institute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_institutes', to='auth.group')),
            ],
        ),
    ]
