# Generated by Django 3.2.25 on 2024-11-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('academic_institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitute',
            name='admins',
            field=models.ForeignKey(blank=True, help_text='Select the group that will manage this Institute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing', to='auth.group'),
        ),
    ]
