# Generated by Django 4.2.17 on 2024-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_institute', '0002_academicinstitute_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitute',
            name='managed_by_import',
            field=models.BooleanField(default=True),
        ),
    ]
