# Generated by Django 4.2.19 on 2025-02-28 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_institute', '0003_academicinstitute_managed_by_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinstitute',
            name='institute',
            field=models.CharField(max_length=500, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
    ]
