# Generated by Django 3.2.23 on 2024-02-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240129_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mos',
            options={'verbose_name': 'MOS', 'verbose_name_plural': 'MOS'},
        ),
    ]
