# Generated by Django 3.2.23 on 2024-02-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
