# Generated by Django 3.2.23 on 2024-02-12 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrecord_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='mos',
            field=models.ForeignKey(blank=True, help_text='Select valid MOS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.mos'),
        ),
    ]
