# Generated by Django 3.2.25 on 2024-11-12 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrecord_mos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='name',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecord',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='ssn',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
