# Generated by Django 4.2.17 on 2024-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmtuser',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
