# Generated by Django 4.2.17 on 2024-12-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_mmtuser_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecord',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='last_name',
            field=models.CharField(default='val', max_length=200),
            preserve_default=False,
        ),
    ]
