# Generated by Django 4.2.20 on 2025-03-10 17:14

import django.core.validators
from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_mmtuser_email_alter_mmtuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='enc_ssn',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(null=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
