# Generated by Django 4.2.20 on 2025-03-10 17:14

from django.db import migrations


def encrypt_ssn(apps, schema_editor):
    UserRecord = apps.get_model("users", "UserRecord")
    for ur in UserRecord.objects.all():
        ur.enc_ssn = ur.ssn
        ur.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userrecord_enc_ssn'),
    ]

    operations = [
        migrations.RunPython(encrypt_ssn),
    ]
