# Generated by Django 4.2.20 on 2025-03-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250310_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='ssn',
        ),
    ]
