# Generated by Django 4.2.20 on 2025-03-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userrecord_ssn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecord',
            old_name='enc_ssn',
            new_name='ssn',
        ),
    ]
