# Generated by Django 3.2.25 on 2024-11-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0001_squashed_0006_auto_20240131_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryCourse_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Set degree start date month and year, January 2050', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Opened', 'Opened'), ('Downloaded', 'Downloaded')], default='Pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
            ],
            options={
                'verbose_name_plural': 'Transcript Status',
            },
        ),
        migrations.RemoveField(
            model_name='acemapping',
            name='academic_course_area',
        ),
        migrations.RemoveField(
            model_name='acemapping',
            name='military_courses',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='user_id',
        ),
        migrations.AddField(
            model_name='academicinstitute',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select the group that will manage requests for this Institute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_institutes', to='auth.group'),
        ),
        migrations.AddField(
            model_name='areasandhour',
            name='military_course',
            field=models.ForeignKey(blank=True, help_text='Choose the relevant military course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.militarycourse'),
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='areas',
            field=models.ManyToManyField(related_name='mappings', through='generate_transcript.AreasAndHour', to='generate_transcript.AcademicCourseArea'),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='academiccoursearea_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generate_transcript.academiccoursearea'),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='code',
            field=models.CharField(help_text='Set course code', max_length=200),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='name',
            field=models.CharField(help_text='Set course name', max_length=500),
        ),
        migrations.AlterField(
            model_name='academicinstitute',
            name='institute',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='institute',
            field=models.ForeignKey(help_text='Choose the affiliated Academic Institute', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='generate_transcript.academicinstitute'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='mos',
            field=models.ManyToManyField(blank=True, help_text='Select valid MOS', related_name='degrees', to='users.MOS'),
        ),
        migrations.AlterField(
            model_name='militarycourse',
            name='course_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddConstraint(
            model_name='areasandhour',
            constraint=models.UniqueConstraint(fields=('academic_course_area', 'degree', 'military_course'), name='unique_connection'),
        ),
        migrations.AddConstraint(
            model_name='areasandhour',
            constraint=models.CheckConstraint(check=models.Q(('degree', None), ('military_course', None), _connector='OR'), name='only_degree_or_mc'),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.UniqueConstraint(fields=('institute', 'degree'), name='unique_degrees'),
        ),
        migrations.DeleteModel(
            name='ACEMapping',
        ),
        migrations.AddField(
            model_name='transcriptstatus',
            name='academic_institute',
            field=models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to='generate_transcript.academicinstitute'),
        ),
        migrations.AddField(
            model_name='transcriptstatus',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Select associated email address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcriptstatus',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.transcript'),
        ),
        migrations.AddField(
            model_name='militarycourse_user',
            name='course',
            field=models.ForeignKey(help_text='Choose the relevant military course', on_delete=django.db.models.deletion.CASCADE, to='generate_transcript.militarycourse'),
        ),
        migrations.AddField(
            model_name='militarycourse_user',
            name='user',
            field=models.ForeignKey(blank=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, to='users.userrecord'),
        ),
    ]
