# Generated by Django 3.2.25 on 2024-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
        ('generate_transcript', '0002_auto_20241120_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarycourse',
            name='user_id',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='military_course', through='generate_transcript.MilitaryCourse_User', to='users.UserRecord'),
        ),
    ]
