# Generated by Django 3.2.25 on 2024-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0003_militarycourse_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasandhour',
            name='level',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
