# Generated by Django 3.2.25 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0004_areasandhour_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarycourse',
            name='course_name',
            field=models.CharField(default='course1', max_length=500),
            preserve_default=False,
        ),
    ]
