# Generated by Django 3.2.25 on 2024-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0005_militarycourse_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarycourse',
            name='ACE_identifier',
            field=models.CharField(default='None Assigned', max_length=250),
        ),
    ]
