# Generated by Django 3.2.25 on 2024-11-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
        ('generate_transcript', '0006_militarycourse_ace_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarycourse_user',
            name='course',
            field=models.ForeignKey(help_text='Choose the relevant military course', on_delete=django.db.models.deletion.CASCADE, related_name='militarycourse_user', to='generate_transcript.militarycourse'),
        ),
        migrations.AlterField(
            model_name='militarycourse_user',
            name='user',
            field=models.ForeignKey(blank=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='militarycourse_user', to='users.userrecord'),
        ),
    ]
