# Generated by Django 3.2.25 on 2024-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
        ('generate_transcript', '0007_auto_20241120_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarycourse',
            name='user_id',
            field=models.ManyToManyField(blank=True, max_length=250, through='generate_transcript.MilitaryCourse_User', to='users.UserRecord'),
        ),
    ]
