# Generated by Django 3.2.25 on 2024-11-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0008_alter_militarycourse_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militarycourse_user',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='militarycourse_user',
            old_name='user',
            new_name='user_id',
        ),
    ]
