# Generated by Django 3.2.25 on 2024-11-21 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_institute', '0002_academicinstitute_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0009_auto_20241120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='institute',
            field=models.ForeignKey(help_text='Choose the affiliated Academic Institute', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='academic_institute.academicinstitute'),
        ),
        migrations.AlterField(
            model_name='transcriptstatus',
            name='academic_institute',
            field=models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_status', to='academic_institute.academicinstitute'),
        ),
        migrations.AlterUniqueTogether(
            name='transcriptstatus',
            unique_together={('transcript', 'recipient'), ('transcript', 'academic_institute')},
        ),
        migrations.DeleteModel(
            name='AcademicInstitute',
        ),
    ]
