# Generated by Django 3.2.25 on 2024-11-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0010_auto_20241121_0438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcriptstatus',
            unique_together=set(),
        ),
    ]
