# Generated by Django 3.2.25 on 2024-12-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0011_alter_transcriptstatus_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militarycourse',
            name='ACE_identifier',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='militarycourse',
            name='user_id',
        ),
        migrations.CreateModel(
            name='MilitaryExperience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('experience_id', models.CharField(max_length=500, unique=True)),
                ('ACE_identifier', models.CharField(default='None Assigned', max_length=250)),
                ('rank', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('areas', models.ManyToManyField(related_name='mappings', through='generate_transcript.AreasAndHour', to='generate_transcript.AcademicCourseArea')),
            ],
        ),
        migrations.AddField(
            model_name='militarycourse',
            name='militaryexperience_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generate_transcript.militaryexperience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areasandhour',
            name='military_course',
            field=models.ForeignKey(blank=True, help_text='Choose the relevant military course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_and_hours', to='generate_transcript.militaryexperience'),
        ),
        migrations.AlterField(
            model_name='militarycourse_user',
            name='course_id',
            field=models.ForeignKey(help_text='Choose the relevant military course', on_delete=django.db.models.deletion.CASCADE, related_name='militarycourse_user', to='generate_transcript.militaryexperience'),
        ),
    ]
