# Generated by Django 3.2.25 on 2024-12-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241112_2034'),
        ('generate_transcript', '0012_auto_20241209_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryexperience',
            name='user_id',
            field=models.ManyToManyField(blank=True, max_length=250, through='generate_transcript.MilitaryCourse_User', to='users.UserRecord'),
        ),
    ]
