# Generated by Django 3.2.25 on 2024-12-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0013_militaryexperience_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militaryexperience',
            old_name='level',
            new_name='rank_level',
        ),
    ]
