# Generated by Django 4.2.17 on 2024-12-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0014_rename_level_militaryexperience_rank_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
