# Generated by Django 4.2.17 on 2024-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0015_militaryexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryexperience',
            name='experience_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
