# Generated by Django 4.2.20 on 2025-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0019_militarytestresult_alter_militarycourse_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarytestresult',
            name='passing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='militarytestresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
