# Generated by Django 4.2.20 on 2025-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0020_alter_militarytestresult_passing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militarytestresult',
            name='score',
        ),
        migrations.AddField(
            model_name='militarycourse_user',
            name='score',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
