# Generated by Django 3.2.23 on 2024-01-31 15:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('email', models.EmailField(blank=True, help_text='Set owner email', max_length=200)),
                ('name', models.CharField(blank=True, help_text='Set owner name', max_length=200)),
                ('description', models.TextField(editable=False, help_text='Set inquiry description')),
                ('subject', models.CharField(editable=False, help_text='Set inquiry subject', max_length=200)),
                ('file', models.FileField(blank=True, help_text='Upload necessary files', null=True, upload_to='inquiries/')),
                ('assigned', models.ForeignKey(blank=True, help_text='Select assigned user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('issue', models.TextField(help_text='Set issue text')),
                ('response', models.TextField(help_text='Set response text')),
                ('default_assigned', models.ForeignKey(blank=True, help_text='Select default assigned group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_faqs', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.TextField(editable=False, help_text='Set comment text')),
                ('inquiry', models.ForeignKey(help_text='Select associated inquiry', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inquiry.inquiry')),
                ('poster', models.ForeignKey(blank=True, help_text='Select comment poster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, help_text='Select inquiry type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry', to='inquiry.inquiryfaq'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Select inquiry owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
