# Generated by Django 3.2.23 on 2024-01-29 21:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20240129_2147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_transcript', '0003_auto_20240129_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_start_date', models.DateField(help_text='Set degree start date month and year, January 2050')),
                ('expected_graduation_date', models.DateField(help_text='Set expected degree end date month and year, January 2050')),
                ('academic_institute', models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='generate_transcript.academicinstitute')),
                ('degree', models.ForeignKey(blank=True, help_text='Select associated degree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='generate_transcript.degree')),
                ('eso', models.ForeignKey(blank=True, help_text='Set ESO for plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_plans', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Set owner/subject of plan', on_delete=django.db.models.deletion.CASCADE, related_name='career_plan', to='users.userrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text='Set required status')),
                ('approved', models.BooleanField(default=False, help_text='Set approved status')),
                ('expected_semester', models.DateField(help_text='Set expected semester date month and year, January 2050')),
                ('course', models.ForeignKey(help_text='Select associated course', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_plans', to='generate_transcript.academiccourse')),
                ('plan', models.ForeignKey(help_text='Select associated plan', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='counseling.careerplan')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.TextField(editable=False, help_text='Set comment text')),
                ('plan', models.ForeignKey(help_text='Select associated plan', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='counseling.careerplan')),
                ('poster', models.ForeignKey(blank=True, help_text='Select comment poster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
