# Generated by Django 3.2.23 on 2024-02-06 22:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counseling', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESONote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('purpose', model_utils.fields.StatusField(choices=[('Advised', 'Advised'), ('Updated', 'Updated'), ('Approved', 'Approved')], default='Advised', max_length=100, no_check_for_status=True)),
                ('note', models.TextField(help_text='Set note text')),
                ('plan', models.ForeignKey(help_text='Select associated plan', on_delete=django.db.models.deletion.CASCADE, related_name='eso_notes', to='counseling.careerplan')),
                ('poster', models.ForeignKey(blank=True, help_text='Select note poster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
