# Generated by Django 3.2.23 on 2024-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_esonote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esonote',
            options={'ordering': ['-created'], 'verbose_name': 'ESO Note', 'verbose_name_plural': 'ESO Notes'},
        ),
        migrations.AddField(
            model_name='courseplan',
            name='hours',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
