# Generated by Django 3.2.25 on 2024-11-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate_transcript', '0001_squashed_0006_auto_20240131_1922'),
        ('counseling', '0005_auto_20240209_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(help_text='Select associated course', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_plans', to='generate_transcript.academiccoursearea'),
        ),
    ]
