# Generated by Django 3.2.25 on 2024-11-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_institute', '0001_initial'),
        ('counseling', '0006_alter_courseplan_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerplan',
            name='academic_institute',
            field=models.ForeignKey(blank=True, help_text='Select associated academic institute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='academic_institute.academicinstitute'),
        ),
    ]
